# -*- coding: utf-8 -*-
"""manchitanam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vnkNbDgIMrg1As6OK5uMekjyQEFUpOT_
"""

# =========================
  # TennisCourtDetector → COCO-14 (Colab one-cell)
  # =========================

  # 0) Installs
  !pip -q install gdown pillow

  import os, zipfile, glob, shutil, json, re, itertools
  from collections import Counter
  from pathlib import Path
  from PIL import Image

  # -------------------------
  # 1) Download & unzip
  # -------------------------
  GDRIVE_ID = "1lhAaeQCmk2y440PmagA0KmIVBIysVMwu"
  ZIP_PATH  = "/content/tennis_court_det_dataset.zip"
  DATA_DIR  = Path("/content/tennis_court_det_dataset")

  # Clean old
  shutil.rmtree(DATA_DIR, ignore_errors=True)
  Path(ZIP_PATH).unlink(missing_ok=True)

  # Download (~7.3 GB)
  !gdown --id "{GDRIVE_ID}" -O "{ZIP_PATH}"

  # Unzip
  DATA_DIR.mkdir(parents=True, exist_ok=True)
  with zipfile.ZipFile(ZIP_PATH, 'r') as z:
      z.extractall(DATA_DIR)

  print("✅ Unzipped to:", DATA_DIR)
  !find "{DATA_DIR}" -maxdepth 2 -type d -print | sed -n '1,30p'
  !find "{DATA_DIR}" -maxdepth 2 -type f | head -n 30

  # -------------------------
  # 2) Quick dataset inspection
  # -------------------------
  files = [p for p in DATA_DIR.rglob("*") if p.is_file()]
  exts = Counter(p.suffix.lower() for p in files)
  print("\nTop file extensions:", exts.most_common(20))

  print("\n=== SAMPLE FILE LIST (first 200) ===")
  for p in sorted(files, key=lambda x: str(x))[:200]:
      print(str(p.relative_to(DATA_DIR)))

  cands = {
      "json": [p for p in files if p.suffix.lower()==".json"],
      "csv" : [p for p in files if p.suffix.lower()==".csv"],
      "txt" : [p for p in files if p.suffix.lower()==".txt"],
      "npy" : [p for p in files if p.suffix.lower()==".npy"],
      "npz" : [p for p in files if p.suffix.lower()==".npz"],
      "mat" : [p for p in files if p.suffix.lower()==".mat"],
  }
  print("\n=== CANDIDATE ANNOTATION FILES ===")
  for k,v in cands.items():
      print(f"{k}: {len(v)} files")
      for p in v[:5]:
          print("  ", p.relative_to(DATA_DIR))

  # -------------------------
  # 3) Peek JSON structure (optional log)
  # -------------------------
  BASE = DATA_DIR / "data"
  TR_JSON = BASE / "data_train.json"
  VA_JSON = BASE / "data_val.json"
  IMG_DIR = BASE / "images"

  def peek(js_path, n=3):
      d = json.loads(js_path.read_text())
      print(f"\n== {js_path} ==")
      if isinstance(d, dict):
          print("Top-level dict keys:", list(d.keys())[:20])
          for k,v in d.items():
              print("Sample item key:", k, "| type:", type(v).__name__)
              if isinstance(v, dict):
                  print("Value keys:", list(v.keys())[:20])
              break
      elif isinstance(d, list):
          print("Top-level list len:", len(d))
          for i, it in enumerate(itertools.islice(d, n)):
              print(f"[{i}] type:", type(it).__name__)
              if isinstance(it, dict):
                  print(" keys:", list(it.keys())[:20])
      else:
          print("Unsupported top-level type:", type(d).__name__)
      return d

  _ = peek(TR_JSON)
  _ = peek(VA_JSON)

  # -------------------------
  # 4) Convert to COCO Keypoints (14 pts)
  # Output: /content/coco14_out/{train,valid}/_annotations.coco.json
  # -------------------------
  OUT = Path("/content/coco14_out")
  (OUT/"train").mkdir(parents=True, exist_ok=True)
  (OUT/"valid").mkdir(parents=True, exist_ok=True)

  KP_NAMES = [f"pt{i+1}" for i in range(14)]  # pt1..pt14
  SKELETON = []  # optional, fill if you want edges like [[1,2],[2,3],...]

  def find_img_for_id(stem: str):
      for ext in (".png", ".jpg", ".jpeg", ".bmp", ".webp"):
          p = IMG_DIR / f"{stem}{ext}"
          if p.exists():
              return p
      # Sometimes JSON stores a path or file name; try direct
      p = IMG_DIR / stem
      return p if p.exists() else None

  def load_pairs(js_path: Path):
      """
      Expects a list of items with fields:
        - "id": image stem (without extension) OR full filename under images/
        - "kps": list of 14 points, each is [x,y] (pixel coordinates)
      """
      data = json.loads(js_path.read_text())
      assert isinstance(data, list), f"{js_path} top-level must be a list"
      pairs, missing, bad = [], 0, 0

      for item in data:
          stem = item.get("id")
          kps  = item.get("kps")
          if not stem or not kps or len(kps) != 14:
              bad += 1
              continue

          img_path = find_img_for_id(stem)
          if not img_path:
              missing += 1
              continue

          pts, ok = [], True
          for p in kps:
              if not (isinstance(p, (list, tuple)) and len(p) >= 2):
                  ok = False; break
              pts.append((float(p[0]), float(p[1])))
          if not ok or len(pts) != 14:
              bad += 1
              continue

          pairs.append((img_path, pts))

      print(f"{js_path.name}: pairs={len(pairs)} | missing_imgs={missing} | malformed={bad}")
      return pairs

  def write_coco(pairs, out_dir: Path):
      out_dir.mkdir(parents=True, exist_ok=True)
      coco = {
          "images": [],
          "annotations": [],
          "categories": [{
              "id": 1, "name": "court", "supercategory": "court",
              "keypoints": KP_NAMES, "skeleton": SKELETON
          }]
      }
      # Copy images + assign IDs
      id_map = {}
      for i, (img_path, _) in enumerate(pairs, start=1):
          dst = out_dir / img_path.name
          if not dst.exists():
              shutil.copy2(img_path, dst)
          w, h = Image.open(img_path).size
          coco["images"].append({"id": i, "file_name": img_path.name, "width": w, "height": h})
          id_map[img_path] = i

      # Annotations
      ann_id = 1
      for img_path, pts in pairs:
          kps = []
          for x, y in pts:
              kps += [x, y, 2.0]  # v=2 (visible)
          coco["annotations"].append({
              "id": ann_id, "image_id": id_map[img_path], "category_id": 1,
              "iscrowd": 0, "bbox": [0,0,0,0], "area": 0,
              "num_keypoints": 14, "keypoints": kps
          })
          ann_id += 1

      out_json = out_dir / "_annotations.coco.json"
      out_json.write_text(json.dumps(coco))
      print(f"📄 Wrote {out_json} | images={len(coco['images'])} | anns={len(coco['annotations'])}")

  # Run conversion
  train_pairs = load_pairs(TR_JSON)
  val_pairs   = load_pairs(VA_JSON)
  assert train_pairs and val_pairs, "No pairs found. Check that image files are named <id>.(png|jpg|jpeg|bmp|webp) and JSON has 14 keypoints."

  write_coco(train_pairs, OUT/"train")
  write_coco(val_pairs,   OUT/"valid")

  print("\n✅ Recap:")
  print(f"  train pairs: {len(train_pairs)}")
  print(f"  valid pairs: {len(val_pairs)}")
  print("Outputs:")
  print("  /content/coco14_out/train/_annotations.coco.json")
  print("  /content/coco14_out/valid/_annotations.coco.json")
  print("  And copied images in their respective folders.")

# Assumes you've already created:
# /content/coco14_out/train/_annotations.coco.json with images in the same folder
# /content/coco14_out/valid/_annotations.coco.json with images in the same folder

!pip -q install ultralytics==8.3.22 pillow
from pathlib import Path
import json, math
from PIL import Image
import shutil, os

COCO_TRAIN = Path("/content/coco14_out/train/_annotations.coco.json")
COCO_VAL   = Path("/content/coco14_out/valid/_annotations.coco.json")

OUT_ROOT   = Path("/content/tennis14_yolo")
IMG_TRAIN  = OUT_ROOT/"images"/"train"
IMG_VAL    = OUT_ROOT/"images"/"val"
LBL_TRAIN  = OUT_ROOT/"labels"/"train"
LBL_VAL    = OUT_ROOT/"labels"/"val"
for p in [IMG_TRAIN, IMG_VAL, LBL_TRAIN, LBL_VAL]: p.mkdir(parents=True, exist_ok=True)

def coco_to_yolo_pose(coco_json_path: Path, img_dst: Path, lbl_dst: Path, num_kp=14, pad=0.05):
    coco = json.loads(coco_json_path.read_text())
    # Build image dict
    id2img = {im["id"]: im for im in coco["images"]}
    # Group anns per image_id (expect one court per image; if more, we’ll write multiple rows)
    img2anns = {}
    for ann in coco["annotations"]:
        if ann.get("num_keypoints", num_kp) != num_kp:
            continue
        img2anns.setdefault(ann["image_id"], []).append(ann)

    # Copy images and write labels
    src_dir = coco_json_path.parent
    kept, skipped = 0, 0
    for img_id, im in id2img.items():
        fname = im["file_name"]
        src = src_dir/fname
        if not src.exists():
            skipped += 1
            continue
        # copy image
        dst = img_dst/fname
        if not dst.exists():
            shutil.copy2(src, dst)

        W, H = Image.open(dst).size
        lbl_path = lbl_dst/(Path(fname).stem + ".txt")
        rows = []

        for ann in img2anns.get(img_id, []):
            kps = ann.get("keypoints", [])
            # Expect [x1,y1,v1,...,x14,y14,v14] in COCO; if your JSON had [x,y] only, you already set v=2 in your exporter
            if len(kps) != num_kp*3:
                continue
            xs = [kps[i] for i in range(0, num_kp*3, 3)]
            ys = [kps[i] for i in range(1, num_kp*3, 3)]
            vs = [kps[i] for i in range(2, num_kp*3, 3)]

            # derive bbox from visible/occluded points; fall back to all points if needed
            use_idx = [i for i,v in enumerate(vs) if v > 0]
            if not use_idx: use_idx = list(range(num_kp))
            xmin, xmax = min(xs[i] for i in use_idx), max(xs[i] for i in use_idx)
            ymin, ymax = min(ys[i] for i in use_idx), max(ys[i] for i in use_idx)
            # pad
            pw, ph = (xmax-xmin), (ymax-ymin)
            xmin -= pad*max(pw,ph); xmax += pad*max(pw,ph)
            ymin -= pad*max(pw,ph); ymax += pad*max(pw,ph)
            xmin, ymin = max(0.0, xmin), max(0.0, ymin)
            xmax, ymax = min(W-1.0, xmax), min(H-1.0, ymax)

            # xywh (normalized)
            w = max(1.0, xmax - xmin); h = max(1.0, ymax - ymin)
            cx = (xmin + xmax) / 2.0; cy = (ymin + ymax) / 2.0
            row = [0, cx/W, cy/H, w/W, h/H]  # class=0 ("court")

            # keypoints normalized + visibility
            for i in range(num_kp):
                px = min(max(xs[i]/W, 0.0), 1.0)
                py = min(max(ys[i]/H, 0.0), 1.0)
                v  = int(vs[i]) if isinstance(vs[i], (int,float)) else 2
                # clamp v to {0,1,2}
                v = 0 if v<=0 else (1 if v==1 else 2)
                row += [px, py, v]

            rows.append(" ".join(str(round(x,6)) if isinstance(x,float) else str(x) for x in row))

        if rows:
            lbl_path.write_text("\n".join(rows))
            kept += 1
    print(f"Converted: labels for {kept} images, skipped {skipped} (missing image or no valid kp).")

coco_to_yolo_pose(COCO_TRAIN, IMG_TRAIN, LBL_TRAIN, num_kp=14, pad=0.06)
coco_to_yolo_pose(COCO_VAL,   IMG_VAL,   LBL_VAL,   num_kp=14, pad=0.06)

# Quick sanity check: show sample label file
import glob, random
some = random.choice(glob.glob(str(LBL_TRAIN/"*.txt")))
print("Sample label:", some, "\n", Path(some).read_text().splitlines()[:2])

yaml = """# tennis court 14-keypoint pose dataset
path: /content/tennis14_yolo
train: images/train
val: images/val

names: [court]
kpt_shape: [14, 3]
# (optional) skeleton: list of pairs, e.g. [[1,2],[2,3],...]
"""
Path("/content/tennis_court_pose14.yaml").write_text(yaml)
print(Path("/content/tennis_court_pose14.yaml").read_text())

from ultralytics import YOLO

# Choose a size. Start small (n) if you saw OOM before, then scale up.
model = YOLO("yolo11m-pose.pt")   # or yolo11s-pose.pt / yolo11m-pose.pt

results = model.train(
    data="/content/tennis_court_pose14.yaml",
    epochs=80,
    imgsz=1280,          # 832–960 is a good range for lines/landmarks
    batch=8,            # drop to 4 if VRAM is tight; you can use accumulate to simulate larger batch
    workers=1,          # Colab-safe
    device=0,
    lr0=0.01, lrf=0.1, weight_decay=5e-4,
    hsv_h=0.0, hsv_s=0.1, hsv_v=0.1,
    degrees=3.0, translate=0.02, scale=0.25, shear=0.0, perspective=0.0,
    flipud=0.0, fliplr=0.0,
    mosaic=0.0, mixup=0.0, copy_paste=0.0,
    name="court14_y11_pose"
)