# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eO-NAvjX9aQojDryGzUmawtVtUugLgqY
"""

# =========================================
# FULL PIPELINE (H100 MAX TUNED)
# - Players: YOLO11m + ByteTrack (imgsz=1280)
# - Court 14-KP: custom pose model (imgsz=2048)
# - Keypoints overlay video -> Ball detector runs on it (imgsz=1280)
# - Ball post-filter: reject candidates overlapping expanded player boxes
# =========================================

!pip install -q ultralytics opencv-python-headless pandas

import cv2
import pandas as pd
import numpy as np
import torch
from ultralytics import YOLO

torch.backends.cudnn.benchmark = True

# ============================================================
# CONFIG
# ============================================================

# ---- INPUT / MODELS ----
VIDEO_PATH        = "/content/test_input_video.mp4"

PLAYER_MODEL_PATH = "yolo11m.pt"          # COCO person
COURT_MODEL_PATH  = "/content/best-2.pt"  # 14 keypoints pose model
BALL_MODEL_PATH   = "/content/best.pt"    # ball model

# ---- OUTPUT PATHS ----
OUT_CSV_RAW                  = "/content/id1_id2_court_ball_RAW.csv"
OUT_VIDEO_FULL_OVERLAY       = "/content/id1_id2_court_ball_overlay_raw.mp4"
KEYPOINTS_VIDEO_FOR_BALL     = "/content/keypoints_for_ball_input.mp4"

# ---- PLAYER TRACKING CONFIG ----
CONF_THRES    = 0.35
IOU_THRES     = 0.50
PLAYER_IMGSZ  = 1280

# Hard-lock IDs (ONLY works if ByteTrack assigns those IDs; see note below)
ID1_TRACK = 1
ID2_TRACK = 2

# ---- TRACKER CONFIG ----
tracker_cfg_try      = "bytetrack.yaml"
tracker_cfg_fallback = "/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/trackers/bytetrack.yaml"

# ---- COURT MODEL CONFIG ----
COURT_IMGSZ   = 1536
COURT_CONF    = 0.22
COURT_IOU     = 0.70
COURT_MAX_DET = 1

# ---- BALL MODEL CONFIG ----
BALL_SOURCE_VIDEO_PATH = KEYPOINTS_VIDEO_FOR_BALL
BALL_IMGSZ   = 1280
BALL_CONF    = 0.30
BALL_IOU     = 0.50
BALL_MAX_DET = 5

# ---- BALL POST-FILTER AGAINST PLAYERS ----
PAD_FRAC = 0.08
MIN_PAD  = 4

# ============================================================
# 0) FRAME AXIS AND FPS
# ============================================================

cap0 = cv2.VideoCapture(VIDEO_PATH)
if not cap0.isOpened():
    raise FileNotFoundError(f"Could not open video: {VIDEO_PATH}")

FPS = cap0.get(cv2.CAP_PROP_FPS)
if FPS is None or FPS <= 0:
    FPS = 24.0

TOTAL_FRAMES = int(cap0.get(cv2.CAP_PROP_FRAME_COUNT))
cap0.release()

print(f"Detected FPS: {FPS}")
print(f"Total frames: {TOTAL_FRAMES}")

FRAME_AXIS = pd.DataFrame({"frame": np.arange(TOTAL_FRAMES)})

# ============================================================
# 1) PLAYER TRACKING (RAW DETECTIONS ONLY)
# ============================================================

print("\n=== Running player tracking (ByteTrack, raw) ===")
player_model = YOLO(PLAYER_MODEL_PATH)

def run_track(tracker_cfg):
    return player_model.track(
        source=VIDEO_PATH,
        tracker=tracker_cfg,
        persist=True,
        conf=CONF_THRES,
        iou=IOU_THRES,
        imgsz=PLAYER_IMGSZ,
        device=0,
        half=True,
        save=False,
        vid_stride=1,
        stream=True
    )

try:
    results_stream = run_track(tracker_cfg_try)
except AssertionError:
    print("Tracker 'bytetrack.yaml' not found at default, using absolute path fallback.")
    results_stream = run_track(tracker_cfg_fallback)

rows = []
frame_idx = 0

for res in results_stream:
    boxes = res.boxes
    if boxes is not None and len(boxes) > 0:
        for b in boxes:
            if not (hasattr(b, "id") and b.id is not None):
                continue

            tid = int(b.id.item())
            cls_id = int(b.cls.item()) if hasattr(b, "cls") else -1
            if cls_id != 0:
                continue

            # keep only the two track IDs you want
            if tid not in [ID1_TRACK, ID2_TRACK]:
                continue

            x1, y1, x2, y2 = b.xyxy[0].tolist()
            cx = (x1 + x2) / 2.0
            cy = (y1 + y2) / 2.0
            conf = float(b.conf.item()) if hasattr(b, "conf") else np.nan

            rows.append({
                "frame": frame_idx,
                "track_id": tid,
                "cx": cx,
                "cy": cy,
                "x1": x1,
                "y1": y1,
                "x2": x2,
                "y2": y2,
                "conf": conf,
            })
    frame_idx += 1

df_det_players = pd.DataFrame(rows)
print("Player dets (raw, track_id 1/2 only) preview:")
print(df_det_players.head())

# Build per-frame id1/id2
per_frame_rows = []
for f in range(TOTAL_FRAMES):
    row = {"frame": f}
    for lab in ["id1", "id2"]:
        row[f"{lab}_cx"]   = np.nan
        row[f"{lab}_cy"]   = np.nan
        row[f"{lab}_x1"]   = np.nan
        row[f"{lab}_y1"]   = np.nan
        row[f"{lab}_x2"]   = np.nan
        row[f"{lab}_y2"]   = np.nan
        row[f"{lab}_conf"] = np.nan

    fdet = df_det_players[df_det_players["frame"] == f]

    sub1 = fdet[fdet["track_id"] == ID1_TRACK]
    if len(sub1):
        best1 = sub1.sort_values("conf", ascending=False).iloc[0]
        row["id1_cx"]   = float(best1["cx"])
        row["id1_cy"]   = float(best1["cy"])
        row["id1_x1"]   = float(best1["x1"])
        row["id1_y1"]   = float(best1["y1"])
        row["id1_x2"]   = float(best1["x2"])
        row["id1_y2"]   = float(best1["y2"])
        row["id1_conf"] = float(best1["conf"])

    sub2 = fdet[fdet["track_id"] == ID2_TRACK]
    if len(sub2):
        best2 = sub2.sort_values("conf", ascending=False).iloc[0]
        row["id2_cx"]   = float(best2["cx"])
        row["id2_cy"]   = float(best2["cy"])
        row["id2_x1"]   = float(best2["x1"])
        row["id2_y1"]   = float(best2["y1"])
        row["id2_x2"]   = float(best2["x2"])
        row["id2_y2"]   = float(best2["y2"])
        row["id2_conf"] = float(best2["conf"])

    per_frame_rows.append(row)

df_id12 = pd.DataFrame(per_frame_rows)

# ============================================================
# 2) COURT 14-KEYPOINT MODEL (RAW, PER-FRAME)
# ============================================================

print("\n=== Running court 14-keypoint model (raw, per-frame) ===")
court_model = YOLO(COURT_MODEL_PATH)

court_rows = []

cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise FileNotFoundError(f"Could not open video for court detection: {VIDEO_PATH}")

frame_idx = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break

    row = {"frame": frame_idx}
    k_xy_out = np.full((14, 2), np.nan, dtype=np.float32)

    res_list = court_model.predict(
        source=frame,
        imgsz=COURT_IMGSZ,
        conf=COURT_CONF,
        iou=COURT_IOU,
        device=0,
        half=True,
        verbose=False,
        max_det=COURT_MAX_DET,
        save=False,
        show=False,
        show_boxes=False,
        show_labels=False,
        show_conf=False
    )

    if len(res_list) > 0 and res_list[0].keypoints is not None and len(res_list[0].keypoints) > 0:
        k_xy_raw = res_list[0].keypoints.xy[0].cpu().numpy()

        if k_xy_raw.shape[0] > 14:
            k_xy_raw = k_xy_raw[:14]
        elif k_xy_raw.shape[0] < 14:
            pad = np.full((14 - k_xy_raw.shape[0], 2), np.nan, dtype=np.float32)
            k_xy_raw = np.concatenate([k_xy_raw, pad], axis=0)

        k_xy_out = k_xy_raw.astype(np.float32)

    for i in range(14):
        x, y = k_xy_out[i, 0], k_xy_out[i, 1]
        row[f"pt{i+1}_x"] = float(x) if not np.isnan(x) else np.nan
        row[f"pt{i+1}_y"] = float(y) if not np.isnan(y) else np.nan

    court_rows.append(row)
    frame_idx += 1

cap.release()

df_court = pd.DataFrame(court_rows)
df_court = FRAME_AXIS.merge(df_court, on="frame", how="left")

# ============================================================
# 2.5) CREATE KEYPOINTS OVERLAY VIDEO FOR BALL DETECTION INPUT
# ============================================================

print("\n=== Creating keypoints overlay video for ball detection input ===")

cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise FileNotFoundError(f"Could not open video for keypoints overlay: {VIDEO_PATH}")

w  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h  = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
if fps is None or fps <= 0:
    fps = FPS

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out_kp = cv2.VideoWriter(KEYPOINTS_VIDEO_FOR_BALL, fourcc, fps, (w, h))

df_court_idx = df_court.set_index("frame")
df_id12_idx  = df_id12.set_index("frame")

# COLORS (BGR)
keypoint_color = (0, 0, 0)      # black
id1_color      = (0, 255, 0)    # green
id2_color      = (255, 0, 0)    # blue

frame_idx = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break

    # ---- court points + TC/BC ----
    if frame_idx in df_court_idx.index:
        row_c = df_court_idx.loc[frame_idx]
        for i in range(14):
            x = row_c.get(f"pt{i+1}_x")
            y = row_c.get(f"pt{i+1}_y")
            if pd.notna(x) and pd.notna(y):
                cv2.circle(frame, (int(x), int(y)), 5, keypoint_color, -1)

        pt1x, pt1y = row_c.get("pt1_x"), row_c.get("pt1_y")
        pt2x, pt2y = row_c.get("pt2_x"), row_c.get("pt2_y")
        pt3x, pt3y = row_c.get("pt3_x"), row_c.get("pt3_y")
        pt4x, pt4y = row_c.get("pt4_x"), row_c.get("pt4_y")

        if pd.notna(pt1x) and pd.notna(pt2x) and pd.notna(pt1y) and pd.notna(pt2y):
            tcx = (pt1x + pt2x) / 2.0
            tcy = (pt1y + pt2y) / 2.0
            cv2.circle(frame, (int(tcx), int(tcy)), 7, keypoint_color, -1)
            cv2.putText(frame, "TC", (int(tcx) + 5, int(tcy) - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, keypoint_color, 2, cv2.LINE_AA)

        if pd.notna(pt3x) and pd.notna(pt4x) and pd.notna(pt3y) and pd.notna(pt4y):
            bcx = (pt3x + pt4x) / 2.0
            bcy = (pt3y + pt4y) / 2.0
            cv2.circle(frame, (int(bcx), int(bcy)), 7, keypoint_color, -1)
            cv2.putText(frame, "BC", (int(bcx) + 5, int(bcy) - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, keypoint_color, 2, cv2.LINE_AA)

    # ---- players ----
    if frame_idx in df_id12_idx.index:
        row_p = df_id12_idx.loc[frame_idx]
        for color, lab in [(id1_color, "id1"), (id2_color, "id2")]:
            x1 = row_p.get(f"{lab}_x1"); y1 = row_p.get(f"{lab}_y1")
            x2 = row_p.get(f"{lab}_x2"); y2 = row_p.get(f"{lab}_y2")
            cx = row_p.get(f"{lab}_cx"); cy = row_p.get(f"{lab}_cy")

            if pd.notna(x1) and pd.notna(y1) and pd.notna(x2) and pd.notna(y2):
                cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)
            if pd.notna(cx) and pd.notna(cy):
                cv2.circle(frame, (int(cx), int(cy)), 6, color, -1)
                cv2.putText(frame, lab, (int(cx) + 5, int(cy) - 5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2, cv2.LINE_AA)

    out_kp.write(frame)
    frame_idx += 1

cap.release()
out_kp.release()
print(f"✅ Keypoints overlay video saved: {KEYPOINTS_VIDEO_FOR_BALL}")

# ============================================================
# 3) BALL DETECTION (RAW) ON KEYPOINTS OVERLAY VIDEO + POST-FILTER
# ============================================================

print("\n=== Running ball detection on keypoints overlay video (post-filter) ===")
ball_model = YOLO(BALL_MODEL_PATH)

ball_rows = []
frame_idx = 0

df_id12_idx = df_id12.set_index("frame") if len(df_id12) else pd.DataFrame().set_index([])

for res in ball_model.predict(
    source=BALL_SOURCE_VIDEO_PATH,
    imgsz=BALL_IMGSZ,
    conf=BALL_CONF,
    iou=BALL_IOU,
    device=0,
    half=True,
    max_det=BALL_MAX_DET,
    verbose=False,
    stream=True,
    save=False,
    vid_stride=1
):
    row = {"frame": frame_idx, "ball_x": np.nan, "ball_y": np.nan, "ball_conf": np.nan}
    boxes = res.boxes
    chosen = None

    if boxes is not None and len(boxes) > 0:
        # best-first order (usually already sorted by conf)
        for bi in range(len(boxes)):
            b = boxes[bi]
            x1, y1, x2, y2 = b.xyxy[0].tolist()
            cx = (x1 + x2) / 2.0
            cy = (y1 + y2) / 2.0
            conf = float(b.conf.item())

            overlaps_player = False
            if frame_idx in df_id12_idx.index:
                row_p = df_id12_idx.loc[frame_idx]
                for lab in ["id1", "id2"]:
                    px1 = row_p.get(f"{lab}_x1"); py1 = row_p.get(f"{lab}_y1")
                    px2 = row_p.get(f"{lab}_x2"); py2 = row_p.get(f"{lab}_y2")
                    if pd.notna(px1) and pd.notna(py1) and pd.notna(px2) and pd.notna(py2):
                        pad_w = max(MIN_PAD, PAD_FRAC * (px2 - px1))
                        pad_h = max(MIN_PAD, PAD_FRAC * (py2 - py1))
                        if (cx >= (px1 - pad_w)) and (cx <= (px2 + pad_w)) and (cy >= (py1 - pad_h)) and (cy <= (py2 + pad_h)):
                            overlaps_player = True
                            break

            if overlaps_player:
                continue

            chosen = (cx, cy, conf)
            break

    if chosen is not None:
        row["ball_x"], row["ball_y"], row["ball_conf"] = float(chosen[0]), float(chosen[1]), float(chosen[2])

    ball_rows.append(row)
    frame_idx += 1

df_ball = pd.DataFrame(ball_rows)
df_ball = FRAME_AXIS.merge(df_ball, on="frame", how="left")

print("Ball preview:")
print(df_ball.head())
print(df_ball.tail())

# ============================================================
# 4) MERGE RAW DETECTIONS INTO SINGLE CSV
# ============================================================

df_raw = FRAME_AXIS.merge(df_id12, on="frame", how="left") \
                   .merge(df_court, on="frame", how="left") \
                   .merge(df_ball, on="frame", how="left", suffixes=("", "_dup"))

dup_cols = [c for c in df_raw.columns if c.endswith("_dup")]
if dup_cols:
    df_raw = df_raw.drop(columns=dup_cols)

print("\nFinal RAW dataframe shape:", df_raw.shape)

df_raw.to_csv(OUT_CSV_RAW, index=False)
print(f"✅ Saved RAW CSV to: {OUT_CSV_RAW}")

# ============================================================
# 5) FULL OVERLAY VIDEO (RAW COORDS + TC/BC + BALL)
# ============================================================

print("\n=== Creating full overlay video (raw coords + TC/BC + ball) ===")

cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise FileNotFoundError(f"Could not open video for overlay: {VIDEO_PATH}")

w  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h  = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
if fps is None or fps <= 0:
    fps = FPS

fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out_vid = cv2.VideoWriter(OUT_VIDEO_FULL_OVERLAY, fourcc, fps, (w, h))

df_idx = df_raw.set_index("frame")

keypoint_color = (0, 0, 0)
id1_color      = (0, 255, 0)
id2_color      = (255, 0, 0)
ball_color     = (0, 0, 255)

frame_idx = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break

    if frame_idx in df_idx.index:
        row = df_idx.loc[frame_idx]

        # court points
        for i in range(14):
            x = row.get(f"pt{i+1}_x")
            y = row.get(f"pt{i+1}_y")
            if pd.notna(x) and pd.notna(y):
                cv2.circle(frame, (int(x), int(y)), 5, keypoint_color, -1)

        pt1x, pt1y = row.get("pt1_x"), row.get("pt1_y")
        pt2x, pt2y = row.get("pt2_x"), row.get("pt2_y")
        pt3x, pt3y = row.get("pt3_x"), row.get("pt3_y")
        pt4x, pt4y = row.get("pt4_x"), row.get("pt4_y")

        if pd.notna(pt1x) and pd.notna(pt2x) and pd.notna(pt1y) and pd.notna(pt2y):
            tcx = (pt1x + pt2x) / 2.0
            tcy = (pt1y + pt2y) / 2.0
            cv2.circle(frame, (int(tcx), int(tcy)), 7, keypoint_color, -1)
            cv2.putText(frame, "TC", (int(tcx) + 5, int(tcy) - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, keypoint_color, 2, cv2.LINE_AA)

        if pd.notna(pt3x) and pd.notna(pt4x) and pd.notna(pt3y) and pd.notna(pt4y):
            bcx = (pt3x + pt4x) / 2.0
            bcy = (pt3y + pt4y) / 2.0
            cv2.circle(frame, (int(bcx), int(bcy)), 7, keypoint_color, -1)
            cv2.putText(frame, "BC", (int(bcx) + 5, int(bcy) - 5),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, keypoint_color, 2, cv2.LINE_AA)

        # players
        for color, lab in [(id1_color, "id1"), (id2_color, "id2")]:
            x1 = row.get(f"{lab}_x1"); y1 = row.get(f"{lab}_y1")
            x2 = row.get(f"{lab}_x2"); y2 = row.get(f"{lab}_y2")
            cx = row.get(f"{lab}_cx"); cy = row.get(f"{lab}_cy")
            if pd.notna(x1) and pd.notna(y1) and pd.notna(x2) and pd.notna(y2):
                cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)
            if pd.notna(cx) and pd.notna(cy):
                cv2.circle(frame, (int(cx), int(cy)), 6, color, -1)
                cv2.putText(frame, lab, (int(cx) + 5, int(cy) - 5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2, cv2.LINE_AA)

        # ball
        bx = row.get("ball_x"); by = row.get("ball_y")
        if pd.notna(bx) and pd.notna(by):
            cv2.circle(frame, (int(bx), int(by)), 5, ball_color, -1)
            cv2.putText(frame, "ball", (int(bx) + 4, int(by) - 4),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.4, ball_color, 1, cv2.LINE_AA)

    out_vid.write(frame)
    frame_idx += 1

cap.release()
out_vid.release()
print(f"✅ Full overlay saved: {OUT_VIDEO_FULL_OVERLAY}")

