# -*- coding: utf-8 -*-
"""playerid_court_points.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX2vmWotePq6xc7GPUXpsp52MY0a2TLA
"""

!pip install -q ultralytics opencv-python-headless pandas

import cv2
import numpy as np
import pandas as pd
import torch
from pathlib import Path
from ultralytics import YOLO

# =========================
# CONFIG
# =========================
VIDEO_PATH        = "/content/test_input_video.mp4"   # your stabilized tennis video
PLAYER_MODEL_PATH = "yolo11m.pt"                      # or your custom player .pt
COURT_MODEL_PATH  = "/content/best-2.pt"              # your 14-kp court pose weights
OUT_CSV           = "/content/fusion_players_court14.csv"
OUTPUT_VIDEO_PATH = "/content/fusion_overlay.mp4"

# Player tracking params
PLAYER_CONF = 0.4
PLAYER_IOU  = 0.5

# Court keypoint params (based on your run_court14_infer.py)
DEVICE       = 0 if torch.cuda.is_available() else "cpu"
COURT_IMGSZ  = 1536
COURT_CONF   = 0.25
COURT_IOU    = 0.70
COURT_MAX_DET = 1

# EMA smoother for court keypoints
ALPHA   = 0.35   # 1.0 = no smoothing, lower = more smoothing
ema_kpts = None  # global state for EMA across frames


# =========================
# 1) PLAYER TRACKING PASS
# =========================
print("=== Pass 1: tracking players with ByteTrack ===")
player_model = YOLO(PLAYER_MODEL_PATH)

# Try built-in tracker name first, fall back to absolute path
tracker_cfg_try      = "bytetrack.yaml"
tracker_cfg_fallback = "/usr/local/lib/python3.12/dist-packages/ultralytics/cfg/trackers/bytetrack.yaml"

def run_player_track(tracker_cfg):
    return player_model.track(
        source=VIDEO_PATH,
        tracker=tracker_cfg,
        persist=True,
        conf=PLAYER_CONF,
        iou=PLAYER_IOU,
        save=False,
        vid_stride=1,
        stream=True
    )

try:
    results_stream = run_player_track(tracker_cfg_try)
except AssertionError:
    print("Tracker 'bytetrack.yaml' not found, using absolute path fallback.")
    results_stream = run_player_track(tracker_cfg_fallback)

track_rows = []
frame_idx = 0

for frame_res in results_stream:
    boxes = frame_res.boxes
    if boxes is not None and len(boxes) > 0:
        for b in boxes:
            # Track ID
            if hasattr(b, "id") and b.id is not None:
                tid = int(b.id.item())
            else:
                tid = -1

            # Bounding box
            x1, y1, x2, y2 = b.xyxy[0].tolist()
            cx = (x1 + x2) / 2.0
            cy = (y1 + y2) / 2.0

            # Confidence and class
            conf   = float(b.conf.item()) if hasattr(b, "conf") else None
            cls_id = int(b.cls.item())    if hasattr(b, "cls")  else None

            track_rows.append({
                "frame": frame_idx,
                "track_id": tid,
                "cls": cls_id,
                "conf": conf,
                "x1": x1, "y1": y1,
                "x2": x2, "y2": y2,
                "cx": cx, "cy": cy
            })
    frame_idx += 1

df_tracks = pd.DataFrame(track_rows)
if df_tracks.empty:
    raise RuntimeError("No detections in player tracking. Check model / conf / video.")

print("Raw tracking rows:", len(df_tracks))

# Pick the 2 main players = 2 most frequent track IDs
id_counts = df_tracks["track_id"].value_counts()
main_ids = list(id_counts.index[:2])
print("Main track IDs (assumed players):", main_ids)

if len(main_ids) < 2:
    print("WARNING: Only one main track ID found. Player2 will be mostly NaN.")

id_to_label = {}
if len(main_ids) >= 1:
    id_to_label[main_ids[0]] = "player1"
if len(main_ids) >= 2:
    id_to_label[main_ids[1]] = "player2"

# Build per-frame table of player centers
frames = sorted(df_tracks["frame"].unique())
player_rows = []

for f in frames:
    row = {"frame": f}
    fdet = df_tracks[df_tracks["frame"] == f]

    for tid, label in id_to_label.items():
        sub = fdet[fdet["track_id"] == tid]
        if len(sub):
            # If ByteTrack somehow produced >1 row for same ID in same frame, take highest conf
            sub_best = sub.sort_values("conf", ascending=False).iloc[0]
            row[f"{label}_px_x"] = float(sub_best["cx"])
            row[f"{label}_px_y"] = float(sub_best["cy"])
        else:
            row[f"{label}_px_x"] = np.nan
            row[f"{label}_px_y"] = np.nan

    player_rows.append(row)

df_players = pd.DataFrame(player_rows)
print("Player per-frame rows:", len(df_players))


# =========================
# 2) COURT KEYPOINT PASS
# =========================
print("=== Pass 2: court 14-keypoint pose ===")
court_model = YOLO(COURT_MODEL_PATH)

cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise SystemExit(f"Could not open video: {VIDEO_PATH}")

frame_idx = 0
court_rows = []
ema_kpts = None   # reset EMA

while True:
    ok, frame = cap.read()
    if not ok:
        break

    # Run pose model on this frame
    res = court_model.predict(
        source=frame,
        imgsz=COURT_IMGSZ,
        conf=COURT_CONF,
        iou=COURT_IOU,
        device=DEVICE,
        verbose=False,
        max_det=COURT_MAX_DET,
        save=False,
        show=False,
        show_boxes=False,
        show_labels=False,
        show_conf=False
    )

    # Default: all NaN
    k_xy    = np.full((14, 2), np.nan, dtype=np.float32)
    k_conf  = np.full((14,),  np.nan, dtype=np.float32)

    if len(res) and len(res[0].keypoints) > 0:
        # first (and only) court instance
        k_xy = res[0].keypoints.xy[0].cpu().numpy()   # (14, 2)
        if res[0].keypoints.conf is not None:
            k_conf = res[0].keypoints.conf[0].cpu().numpy()
        else:
            k_conf = np.ones((k_xy.shape[0],), dtype=np.float32)

        # EMA smoothing (on coordinates only)
        if ema_kpts is None:
            ema_kpts = k_xy
        else:
            ema_kpts = ALPHA * k_xy + (1.0 - ALPHA) * ema_kpts

        k_xy = ema_kpts  # use smoothed

    # Build row
    row = {"frame": frame_idx}
    for i in range(14):
        row[f"pt{i+1}_x"]    = float(k_xy[i, 0]) if not np.isnan(k_xy[i, 0]) else np.nan
        row[f"pt{i+1}_y"]    = float(k_xy[i, 1]) if not np.isnan(k_xy[i, 1]) else np.nan
        row[f"pt{i+1}_conf"] = float(k_conf[i])  if not np.isnan(k_conf[i])  else np.nan

    court_rows.append(row)
    frame_idx += 1

cap.release()

df_court = pd.DataFrame(court_rows)
print("Court per-frame rows:", len(df_court))


# =========================
# 3) MERGE → FINAL CSV
# =========================
print("=== Merging players + court keypoints ===")
df_fusion = pd.merge(df_court, df_players, on="frame", how="outer").sort_values("frame")

# Reorder columns nicely
cols = ["frame"]
for label in ["player1", "player2"]:
    cols += [f"{label}_px_x", f"{label}_px_y"]
for i in range(14):
    cols += [f"pt{i+1}_x", f"pt{i+1}_y", f"pt{i+1}_conf"]

# Keep only columns that actually exist (in case player2_x/y missing)
cols = [c for c in cols if c in df_fusion.columns]
df_fusion = df_fusion[cols]

df_fusion.to_csv(OUT_CSV, index=False)
print("✅ Saved fusion CSV to:", OUT_CSV)
print(df_fusion.head())


# =========================
# 4) VISUAL OVERLAY VIDEO
# =========================
print("=== Rendering overlay video ===")

cap = cv2.VideoCapture(VIDEO_PATH)
fps = cap.get(cv2.CAP_PROP_FPS)
w   = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h   = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fourcc = cv2.VideoWriter_fourcc(*"mp4v")
out_vid = cv2.VideoWriter(OUTPUT_VIDEO_PATH, fourcc, fps, (w, h))

for _, row in df_fusion.iterrows():
    ret, frame = cap.read()
    if not ret:
        break

    # draw court keypoints (yellow)
    for i in range(14):
        x = row.get(f"pt{i+1}_x", np.nan)
        y = row.get(f"pt{i+1}_y", np.nan)
        if not np.isnan(x) and not np.isnan(y):
            cv2.circle(frame, (int(x), int(y)), 6, (0, 255, 255), -1)

    # draw players: player1 = green, player2 = blue
    for color, label in [((0,255,0),"player1"), ((255,0,0),"player2")]:
        px = row.get(f"{label}_px_x", np.nan)
        py = row.get(f"{label}_px_y", np.nan)
        if not np.isnan(px) and not np.isnan(py):
            cv2.circle(frame, (int(px), int(py)), 12, color, -1)
            cv2.putText(
                frame,
                label,
                (int(px) - 25, int(py) - 15),
                cv2.FONT_HERSHEY_SIMPLEX,
                0.6,
                color,
                2,
                cv2.LINE_AA
            )

    out_vid.write(frame)

cap.release()
out_vid.release()
print("✅ Overlay video saved to:", OUTPUT_VIDEO_PATH)

import pandas as pd

pd.read_csv("fusion_players_court14.csv")

import pandas as pd
df = pd.read_csv("/content/fusion_players_court14.csv")

print("Total frames:", len(df))
print("Frame continuity:", "OK" if df["frame"].diff().fillna(1).eq(1).all() else "BROKEN")

for label in ["player1", "player2"]:
    if f"{label}_px_x" in df:
        nan_pct = df[[f"{label}_px_x", f"{label}_px_y"]].isna().mean().mean() * 100
        print(f"{label} missing %:", round(nan_pct, 2))

for label in ["player1", "player2"]:
    if f"{label}_x1" in df:
        invalid_boxes = (df[f"{label}_x2"] <= df[f"{label}_x1"]).sum()
        print(f"{label} invalid boxes:", invalid_boxes)

print("\nCoordinate range check:")
print(df.describe()[["player1_px_x", "player1_px_y", "player2_px_x", "player2_px_y"]])

